apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpower-web-mpvroot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: "managed-nfs-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpower-web-siteconf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: "managed-nfs-storage"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      hostAliases:
        - ip: "10.10.18.10"
          hostnames:
          - "win-8tj9gnmsmhe"
      containers:
        - command: ["/usr/local/bin/webserver-entrypoint.sh"]
          args:
            - httpd
            #- none
          env:
            - name: DB_CONTAINER_NAME
              value: acustomer-mpowerdb-headless
            - name: DB_KIND
              value: __MYSQL
            - name: DB_PORT
              value: "3306"
            - name: GLOBAL_VAL_NAME
              value: rnd-main
            - name: HOST_INDEX
              value: _01
            - name: INSTALL_APP_WEB
              value: "10"
            - name: SFTP_ADDR
              value: "10.10.4.53"
            - name: SFTP_PWD
              value: "@mpower4119.!"
            - name: SFTP_USER
              value: "mpower"
            - name: SVN_PWD
              value: "svn@123"
            - name: SVN_USER
              value: "build"
            - name: MPOWER_K8S
              value: "1"
          image: 10.10.4.59:5000/rnd/webserver:8_2.4.58_8.2.15_240215
          name: webserver
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: web-mpvroot
              mountPath: /data1
            - name: web-siteconf
              mountPath: /MOCOMSYS/site_props
      initContainers:
        - name: webserver-init
          image: 10.10.4.59:5000/rnd/webserver:8_2.4.58_8.2.15_240215
          command: ["sh", "-c"]
          args:
            - chown mpower:mpower /data1;
              chown mpower:mpower /MOCOMSYS/site_props;
          volumeMounts:
            - name: web-mpvroot
              mountPath: /data1
            - name: web-siteconf
              mountPath: /MOCOMSYS/site_props
          securityContext:
            runAsUser: 0
      restartPolicy: Always
      volumes:
        - name: web-mpvroot
          persistentVolumeClaim:
            claimName: mpower-web-mpvroot
        - name: web-siteconf
          persistentVolumeClaim:
            claimName: mpower-web-siteconf
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-headless
  labels:
    app: webserver-headless
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  clusterIP: None
  selector:
    app: webserver
